service: aws

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: us-east-1

resources:
  Resources:
    MySqsQueue:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: sqs
        TopicArn: arn:aws:sns:us-east-1:328367910941:testesns.fifo
        Endpoint: arn:aws:sqs:us-east-1:328367910941:testecarol.fifo
        
    
    testecarol:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: testecarol.fifo
        VisibilityTimeout: 300
        FifoQueue: true
        ContentBasedDeduplication: true
 