
service: logs-metrics

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  log:
    handler: handler.log
    events:
     - schedule: 
        enabled: true
        rate: rate(1 day)
    Role: !GetAtt
      - CloudWatchLogsRole
      - Arn

resources:
  Resources:
    EscalationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: teste-topic

    EscalationTopicEmailSubscriber:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: caroline.cunha.b@hotmail.com
        Protocol: email
        TopicArn: !Ref EscalationTopic

    CloudFrontTotalErrorRateAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        ActionsEnabled: true
        AlarmName: "[Notif][ASG][Lambda] Elevated error volume"
        Namespace: 'teste-carol'
        MetricName: '% of Success'
        Statistic: Sum
        Period: 300
        EvaluationPeriods: 1
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Threshold: 1
        AlarmActions:
          - !Ref EscalationTopic