# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: logs-metrics
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: us-east-1

functions:
  log:
    handler: handler.log
    events:
     - schedule: 
        enabled: false
        rate: rate(1 day)
    Role: !GetAtt
      - CloudWatchLogsRole
      - Arn

resources:
  Resources:
    CloudWatchLogsRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: ["ec2.amazonaws.com"]
              Action: ["sts:AssumeRole"]
        Policies:
          - PolicyName: AppLogsPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    [
                      "logs:CreateLogGroup",
                      "logs:CreateLogStream",
                      "logs:GetLogEvents",
                      "logs:PutLogEvents",
                      "logs:DescribeLogGroups",
                      "logs:DescribeLogStreams",
                      "logs:FilterLogEvents",
                      "logs:PutRetentionPolicy",
                      "cloudwatch:PutMetricData",
                      "logs:GetQueryResults",
                      "logs:StartQuery"
                    ]
                  Resource: "*"